# Generated by Django 4.2 on 2023-04-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'enquiry',
            },
        ),
    ]
